
  final Map<String, String> categoryImages = {
    "beauty":"images/mackup.png",
     "fragrances":"images/beauty.png",
    "furniture":"images/furniture.png",
    "groceries":"images/groceries.png",
    "home-decoration":"images/house-decoration.png",
    "kitchen-accessories":"images/kitchen.png",
    "laptops":"images/laptop.png",
    "mens-shirts":"images/shirt.png",
    "mens-shoes":"images/classic.png",
    "mens-watches":"images/wrist-watch.png",
    "mobile-accessories":"images/laptop.png",
    "motorcycle":"images/car.png",
    "skin-care":"images/skincare.png",
    "smartphones":"images/phone.png",
    "sports-accessories":"images/beauty.png",
    "sunglasses":"images/sunglasses.png",
    "tablets":"images/tablet.png",
    "tops":"images/beauty.png",
    "vehicle":"images/car.png",
    "womens-bags":"images/handbag.png",
    "womens-dresses":"images/woman-clothes.png",
    "womens-jewellery":"images/mackup.png",
    "womens-shoes":"images/classic.png",
    "womens-watches":"images/wrist-watch.png",
  };